version: '3.8'

services:
  reporter:
    build:
      context: ../..
      dockerfile: packages/reporter-server/Dockerfile
    ports:
      - "8400:8400"
    environment:
      - REPORTER_PORT=8400
      - REPORTER_ARTIFACTS_DIR=/data/artifacts
      - REPORTER_SNAPSHOTS_DIR=/data/snapshots
      - REPORTER_DB_DIR=/data/db
      - REPORTER_LOG_LEVEL=info
      # DB properties will default to localhost inside the container
    volumes:
      - reporter-data:/data

volumes:
  reporter-data:
